### ISSUE TITLE
运行报错。提示something wrong

### ISSUE THREAD

**Issue by lovefox666** [ladingwu/-#7]
something wrong
Traceback (most recent call last):
  File "e:\01.Projects\identfying_code_recognize-master\python_recognize.py", line 147, in <module>
    recognize_picture(p,i)
  File "e:\01.Projects\identfying_code_recognize-master\python_recognize.py", line 111, in recognize_picture
    if pix3[int(x3*2),y3] == 0:
IndexError: image index out of range
识别了0张验证码 正确率为0.0%

**Comment by liu165** [comment]
难搞哦
